on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    using: 'node12'
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: maven
          package-name: geosciences-data-pipelines